name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature you'd like.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered?
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - SEO Analysis Engine
        - Admin Dashboard
        - API Endpoints
        - i18n / Translations
        - Meta Fields
        - Readability
        - Redirects
        - Sitemap
        - Other
    validations:
      required: true
