// Client-side exports — React components for Payload admin UI
// "use client" is prepended by tsup onSuccess (see tsup.config.ts)
export { default as SeoAnalyzerField } from './components/SeoAnalyzer.js'
export { SeoView } from './components/SeoView.js'
export { default as SeoNavLink } from './components/SeoNavLink.js'
export { ContentDecaySection } from './components/ContentDecaySection.js'
export { default as ScoreHistoryChart } from './components/ScoreHistoryChart.js'
export { SitemapAuditView } from './components/SitemapAuditView.js'
export { SeoConfigView } from './components/SeoConfigView.js'
export { SeoSocialPreview } from './components/SeoSocialPreview.js'
export { RedirectManagerView } from './components/RedirectManagerView.js'
export { CannibalizationView } from './components/CannibalizationView.js'
export { SchemaBuilderView } from './components/SchemaBuilderView.js'
export { PerformanceView } from './components/PerformanceView.js'
export { KeywordResearchView } from './components/KeywordResearchView.js'
export { LinkGraphView } from './components/LinkGraphView.js'
